name: Check for updates

concurrency:
  group: checkupdate
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  checkupdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'
    - name: Publish version
      run: python3 scripts/check-updates.py